name: Update to latest version

on:
  workflow_dispatch:
  schedule:
  - cron: '00 12 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install tools
      run: |
        go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
        go get github.com/brancz/gojsontoyaml
        go get github.com/google/go-jsonnet/cmd/jsonnet
    - name: Run jb update
      run: jb update
    - name: Run build script
      run: ./build.sh example.jsonnet
    - name: Create kustomization
      uses: imranismail/setup-kustomize@v1
    - run: |
        #!/usr/bin/env bash
        KUSTOMIZATION1=./manifest/setup/kustomization.yaml
        KUSTOMIZATION2=./manifest/setup/kustomization.yaml
        if [ -f "$KUSTOMIZATION1" ];
          then rm "$KUSTOMIZATION1"
        fi
        if [ -f "$KUSTOMIZATION2" ];
          then rm "$KUSTOMIZATION2"
        fi
        sh -c 'cd manifests/setup && kustomization create --autodetect'
        sh -c 'cd manifests/deploy && kustomization create --autodetect'
    - name: Cleanup
      run: rm -rf ./vendor
    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
        title: "[bot] Automated update"
        signoff: false
        committer: Github <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: |
          This is an automated update to manifests and jsonnet dependencies from CI.

          Configuration of the workflow is located in `.github.com/workflows/update.yaml`
        labels: bot/update
